# Form implementation generated from reading ui file 'ac.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 330)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 80, 80, 26))
        self.pushButton.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 80, 81, 26))
        self.pushButton_2.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 130, 80, 26))
        self.pushButton_3.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 130, 81, 26))
        self.pushButton_4.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 180, 80, 26))
        self.pushButton_5.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 180, 81, 26))
        self.pushButton_6.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 230, 80, 26))
        self.pushButton_7.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(130, 230, 81, 26))
        self.pushButton_8.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 280, 81, 26))
        self.pushButton_9.setStyleSheet("background-color: = rgb(200, 255, 251)\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(130, 280, 81, 26))
        self.pushButton_10.setStyleSheet("background-color: = rgb(200, 255, 251)\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 40, 191, 26))
        self.pushButton_11.setStyleSheet("background-color: = rgb(200, 255, 251)")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 10, 80, 26))
        self.pushButton_12.setStyleSheet("background-color: = rgb(255, 10, 7)")
        self.pushButton_12.setObjectName("pushButton_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "1º Semestre"))
        self.pushButton_2.setText(_translate("Form", "2º Semestre"))
        self.pushButton_3.setText(_translate("Form", "3º Semestre"))
        self.pushButton_4.setText(_translate("Form", "4º Semestre"))
        self.pushButton_5.setText(_translate("Form", "5º Semestre"))
        self.pushButton_6.setText(_translate("Form", "6º Semestre"))
        self.pushButton_7.setText(_translate("Form", "7º Semestre"))
        self.pushButton_8.setText(_translate("Form", "8º Semestre"))
        self.pushButton_9.setText(_translate("Form", "9º Semestre"))
        self.pushButton_10.setText(_translate("Form", "10º Semestre"))
        self.pushButton_11.setText(_translate("Form", "completo"))
        self.pushButton_12.setText(_translate("Form", "return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
