# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(300, 639)
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 20, 271, 81))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 191, 16))
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 30, 21, 16))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 30, 21, 16))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(120, 30, 31, 16))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(160, 30, 21, 16))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 71, 16))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(90, 50, 151, 16))
        self.frame_2 = QFrame(Form)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 110, 271, 81))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 251, 16))
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 30, 21, 16))
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 30, 61, 16))
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(120, 30, 31, 16))
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(160, 30, 51, 16))
        self.label_13 = QLabel(self.frame_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 50, 71, 16))
        self.label_14 = QLabel(self.frame_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(90, 50, 151, 16))
        self.frame_3 = QFrame(Form)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 210, 271, 81))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_15 = QLabel(self.frame_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 10, 251, 16))
        self.label_16 = QLabel(self.frame_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 30, 21, 16))
        self.label_17 = QLabel(self.frame_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 30, 61, 16))
        self.label_18 = QLabel(self.frame_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(120, 30, 31, 16))
        self.label_19 = QLabel(self.frame_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(160, 30, 81, 16))
        self.label_20 = QLabel(self.frame_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 50, 71, 16))
        self.label_21 = QLabel(self.frame_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(90, 50, 171, 16))
        self.frame_4 = QFrame(Form)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 310, 271, 81))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_22 = QLabel(self.frame_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 10, 251, 16))
        self.label_23 = QLabel(self.frame_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 30, 21, 16))
        self.label_24 = QLabel(self.frame_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(40, 30, 71, 16))
        self.label_25 = QLabel(self.frame_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(120, 30, 31, 16))
        self.label_26 = QLabel(self.frame_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(160, 30, 91, 16))
        self.label_27 = QLabel(self.frame_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 50, 71, 16))
        self.label_28 = QLabel(self.frame_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(90, 50, 171, 16))
        self.frame_5 = QFrame(Form)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 410, 271, 81))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.label_29 = QLabel(self.frame_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 10, 251, 16))
        self.label_30 = QLabel(self.frame_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 30, 21, 16))
        self.label_31 = QLabel(self.frame_5)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(40, 30, 61, 16))
        self.label_32 = QLabel(self.frame_5)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(120, 30, 31, 16))
        self.label_33 = QLabel(self.frame_5)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(160, 30, 91, 16))
        self.label_34 = QLabel(self.frame_5)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 50, 71, 16))
        self.label_35 = QLabel(self.frame_5)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(90, 50, 171, 16))
        self.frame_6 = QFrame(Form)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 510, 271, 81))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_36 = QLabel(self.frame_6)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 10, 251, 16))
        self.label_37 = QLabel(self.frame_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 30, 21, 16))
        self.label_38 = QLabel(self.frame_6)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(40, 30, 71, 16))
        self.label_39 = QLabel(self.frame_6)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(120, 30, 31, 16))
        self.label_40 = QLabel(self.frame_6)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(160, 30, 81, 16))
        self.label_41 = QLabel(self.frame_6)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 50, 71, 16))
        self.label_42 = QLabel(self.frame_6)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(90, 50, 161, 16))
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 600, 80, 26))
        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(200, 600, 80, 26))
        self.pushButton_3 = QPushButton(Form)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(110, 600, 71, 26))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"CH:", None))
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("Form", u"CRE:", None))
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("Form", u"SITUACAO:", None))
        self.label_7.setText("")
        self.label_8.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"CH:", None))
        self.label_10.setText("")
        self.label_11.setText(QCoreApplication.translate("Form", u"CRE:", None))
        self.label_12.setText("")
        self.label_13.setText(QCoreApplication.translate("Form", u"SITUACAO:", None))
        self.label_14.setText("")
        self.label_15.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"CH:", None))
        self.label_17.setText("")
        self.label_18.setText(QCoreApplication.translate("Form", u"CRE:", None))
        self.label_19.setText("")
        self.label_20.setText(QCoreApplication.translate("Form", u"SITUACAO:", None))
        self.label_21.setText("")
        self.label_22.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"CH:", None))
        self.label_24.setText("")
        self.label_25.setText(QCoreApplication.translate("Form", u"CRE:", None))
        self.label_26.setText("")
        self.label_27.setText(QCoreApplication.translate("Form", u"SITUACAO:", None))
        self.label_28.setText("")
        self.label_29.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"CH:", None))
        self.label_31.setText("")
        self.label_32.setText(QCoreApplication.translate("Form", u"CRE:", None))
        self.label_33.setText("")
        self.label_34.setText(QCoreApplication.translate("Form", u"SITUACAO:", None))
        self.label_35.setText("")
        self.label_36.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_37.setText(QCoreApplication.translate("Form", u"CH:", None))
        self.label_38.setText("")
        self.label_39.setText(QCoreApplication.translate("Form", u"CRE:", None))
        self.label_40.setText("")
        self.label_41.setText(QCoreApplication.translate("Form", u"SITUACAO:", None))
        self.label_42.setText("")
        self.pushButton.setText(QCoreApplication.translate("Form", u"Retornar", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Proximo", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"Anterior", None))
    # retranslateUi

